/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package quotes;

import com.google.gson.Gson;

import java.io.FileNotFoundException;
import java.io.FileReader;

public class App {
    public static void main(String[] args) throws FileNotFoundException {
        Gson gson = new Gson();

        Quote[] quotes = gson.fromJson(new FileReader("src/main/resources/quotes.json"),Quote[].class);
        Quote random = quotes[randomizeQuotes(quotes.length)];
        System.out.println(random);
    }

    public static int randomizeQuotes(int max) {
        int x = (int)(Math.random() * max);
        return x;
    }

}

