/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package quotes;

import com.google.gson.Gson;

import java.io.FileNotFoundException;
import java.io.FileReader;

public class App {
    public static void main(String[] args) throws FileNotFoundException {
        Gson gson = new Gson();

        Quote[] parseSource = gson.fromJson(new FileReader("resources/quotes.json"),Quote[].class);
        int index = randomizeQuotes(parseSource.length);
        Quote random = parseSource[index];
    }

    public static int randomizeQuotes(int max) {
        int x = (int)(Math.random() * max);
        return x;
    }

}

